### PR TITLE
chore: add eslint plugin prettier and rule to prevent one var

### PR DESCRIPTION
**Pull request by david10sing**
**Description**
This is a PR to make eslint and prettier work better together.

The goal is to have prettier and eslint show errors and in the developer's editor.

This is following the `eslint-plugin-prettier` [README](https://github.com/prettier/eslint-plugin-prettier) to setup the plugin.

**How to test**
1. In your IDE (I use vscode), try to chain create const like so `const foo = 'bar', baz: 'foo'`
2. Confirm you see an eslint message like the following

Screenshot from 2022-12-24 07-34-07

3. After saving your file, confirm it fixes (if you have this enabled in your IDE) like so

Screenshot from 2022-12-24 07-35-04

### CODE REVIEW

**Comment by castarco** [comment]
Can you rebase this PR on `main`, please?

**Comment by david10sing** [comment]
Hi

@castarco 

Thank you. I've rebased and fixed the eslint errors in the `index.ts` file.

Could you please have a look and run some test please.

Thank you.

**Comment by david10sing** [comment]
@castarco 

Is it ok to get an approval on this please.

Cheers

**Review by castarco — APPROVED** [review]
LGTM!

**Comment by castarco** [comment]
All good, sorry for the delay, I've been quite busy these past weeks >_< .

**Pull request merged**
