### PR TITLE
fix(#46): add pnpm as a dev deps

### PR DESCRIPTION
**Pull request by david10sing**
- git hooks and tests making use of pnpm but other contributors might now have pnpm
- adding as a dev deps to the repo so all is well
- Also used `npm` in the pre-commit hooks as it ships with node

### CODE REVIEW

**Comment by david10sing** [comment]
@ShogunPanda 

Could I get a review on this please?

Thank you

**Comment by ShogunPanda** [comment]
I'm conflicted on this. It's formally fine but I'm not sure if we want it or not.

@micheleriva Thoughts?

**Comment by ShogunPanda** [comment]
To clarify, I would just change the husky commit hook and leave the rest unchanged.

**Comment by david10sing** [comment]
@ShogunPanda 

The test is using `pnpm` and the pre-commit hook is running the test. So if I only change the pre-commit hook, it will still prevent me from creating a commit.

**Comment by ShogunPanda** [comment]
Can't you just change a single line in non too much important files like .git ignore?

**Comment by david10sing** [comment]
@ShogunPanda 

I am not quite sure what you mean by that.

Is there an example of what you mean? I could run a commit with `--no-verify` to skip the git hooks but that just defeats the purpose of having them in the first place.

Look forward to your response.

Regards

**Comment by ShogunPanda** [comment]
Sorry, I misunderstood.

For a commit that does not affect the functional source code (like this) you can definitely skip hooks when creating the commit.

**Comment by david10sing** [comment]
Yes. That is fine for such commit.

But I have other branches with commit touching the source code and without `pnpm`, I won't be able to commit them.

**Comment by ShogunPanda** [comment]
I think I'm losing context here, sorry.

What I was talking about is to change the husky hook to use NPM and commit changes. If (sorry, I can't check code at the moment) package.json references pnpm in any script change it as well. Leave all the rest unchanged.

Once this is merged you will be unlocked for local development. What we use in CI pipeline is not relevant.

Are we on the same page?

**Comment by ShogunPanda** [comment]
@david10sing Can you clarify why you close this? Is there anything we have to do here?

**Pull request closed without merging**
